#cloud-config
hostname: core02
coreos:
  etcd:
    discovery: https://discovery.etcd.io/ee9da7534b74afbd89716b151789f24a
    addr: 10.0.0.2:4001
    peer-addr: 10.0.0.2:7001
  units:
    - name: etcd.service
      command: start
    - name: fleet.service
      command: start
    - name: 00-eth0.network
      runtime: true
      content: |
        [Match]
        Name=enp0s25

        [Network]
        DNS=10.0.0.1
        Address=10.0.0.2/13
        Gateway=10.0.0.254
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsqEEmCLP3Zw6nm8+PnLZmS83OgqtwLp1GWQOu4PgPPZTzpms0FPcaQwm35wxoYqZMBH67ZaNNaBm+pfgCtQq0uMABOfPitOAm9e1MAkaFUr+Tvc4dpjOGgyClEkWXl0wyZCvWowUnN3MniDHvq/hGd/Moof95YOxDmaO/PW5jFPQ6laRMdDMyDVDv7rGZregqUe8nUsLAneaeTQf6vM9JuIYYhyrwUOA71x99wBowUS8L6HMu5LNHYx4as86ipwZNHcgWaDpYfFDpw3+LoEwPLAGAeMIgEyN7k9iXR6JSkO3P8x7fESRxIS0tyt7pqzo8WDkEhZdeehd3gpg/rDIv

users:
  - name: worker
    passwd: $6$rounds=4096$IDbL4xGuQW8jK1$iTykwSuPJ1ZdeL6NQp8eP/5yckSphg4x7US6d4kao2sNCNtAtr4rVMKvfp0oyGz3LyYaimZLseds/6/lXfJnL.
    groups:
      - sudo
      - docker
    ssh-authorized-keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCsqEEmCLP3Zw6nm8+PnLZmS83OgqtwLp1GWQOu4PgPPZTzpms0FPcaQwm35wxoYqZMBH67ZaNNaBm+pfgCtQq0uMABOfPitOAm9e1MAkaFUr+Tvc4dpjOGgyClEkWXl0wyZCvWowUnN3MniDHvq/hGd/Moof95YOxDmaO/PW5jFPQ6laRMdDMyDVDv7rGZregqUe8nUsLAneaeTQf6vM9JuIYYhyrwUOA71x99wBowUS8L6HMu5LNHYx4as86ipwZNHcgWaDpYfFDpw3+LoEwPLAGAeMIgEyN7k9iXR6JSkO3P8x7fESRxIS0tyt7pqzo8WDkEhZdeehd3gpg/rDIv
